spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ledgerx?serverTimezone=Asia/Tokyo&characterEncoding=utf8
    username: ledgerx
    password: ledgerx_123
  jpa:
    hibernate:
      ddl-auto: none     # 你已经手写了建表 SQL，就不要自动建表了
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id   # GitHub 用户唯一 id
ledgerx:
  auth:
    signup-token-ttl: 15m
  webauthn:
    enabled: true
    rpName: "LedgerX"
    rpId: "localhost"
    origins:
      - "http://localhost:3000"
    challengeTtlSeconds: 300
